// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoNyyL3hPG440SivZ8ybwkHFjEQXrbQNE',
    appId: '1:929460459024:web:82aaa284a360221e1d1c95',
    messagingSenderId: '929460459024',
    projectId: 'genai-807bd',
    authDomain: 'genai-807bd.firebaseapp.com',
    storageBucket: 'genai-807bd.firebasestorage.app',
    measurementId: 'G-BHM77ETH9N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzdL5_suJUXKd9b-JzPHRl1_6y62GInH4',
    appId: '1:929460459024:android:d7484e4526d22ea11d1c95',
    messagingSenderId: '929460459024',
    projectId: 'genai-807bd',
    storageBucket: 'genai-807bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjpqwMfrQsASmsADFJWoLkYF6u7NSXHFw',
    appId: '1:929460459024:ios:24f260fdb7188def1d1c95',
    messagingSenderId: '929460459024',
    projectId: 'genai-807bd',
    storageBucket: 'genai-807bd.firebasestorage.app',
    iosBundleId: 'com.example.artisans',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjpqwMfrQsASmsADFJWoLkYF6u7NSXHFw',
    appId: '1:929460459024:ios:24f260fdb7188def1d1c95',
    messagingSenderId: '929460459024',
    projectId: 'genai-807bd',
    storageBucket: 'genai-807bd.firebasestorage.app',
    iosBundleId: 'com.example.artisans',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoNyyL3hPG440SivZ8ybwkHFjEQXrbQNE',
    appId: '1:929460459024:web:c740f17d239246da1d1c95',
    messagingSenderId: '929460459024',
    projectId: 'genai-807bd',
    authDomain: 'genai-807bd.firebaseapp.com',
    storageBucket: 'genai-807bd.firebasestorage.app',
    measurementId: 'G-2XFSE0HSEQ',
  );
}
