"""In-memory stand-ins for the Google Cloud services, for tests and for ARTISAN_FAKE_CLOUD=1 local runs.

They return fixed, clearly fake data, so the API and the Flutter app can be exercised without a GCP project.
"""
import base64
import datetime as dt
import json

# A 1x1 transparent PNG, returned by the fake image editor.
TINY_PNG = base64.b64decode(
    "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==")


class FakeStorage:
    def __init__(self):
        self.objects = {}

    def check(self):
        pass

    def upload_public(self, object_name, data, content_type):
        self.objects[object_name] = (data, content_type)
        return f"https://storage.example/fake-bucket/{object_name}", f"gs://fake-bucket/{object_name}"


class FakeStore:
    def __init__(self, orders=None, products=None):
        now = dt.datetime.now()
        self.orders = orders if orders is not None else [
            {"id": "o1", "created_at": now - dt.timedelta(days=2), "owner_split": {"demo-user": 1200.0},
             "items": [{"product_id": "p1", "qty": 2, "price_at_purchase": 600.0}]},
            {"id": "o2", "created_at": now - dt.timedelta(days=10), "owner_split": {"demo-user": 850.0},
             "items": [{"product_id": "p2", "qty": 1, "price_at_purchase": 850.0}]},
        ]
        self.products = products if products is not None else [
            {"id": "p1", "owner_id": "demo-user", "title": "Hand-block printed Ajrakh stole", "price": 600.0},
            {"id": "p2", "owner_id": "demo-user", "title": "Dhokra brass elephant", "price": 850.0},
        ]

    def orders_since(self, start):
        return [o for o in self.orders if o["created_at"] >= start]

    def products_of(self, owner_id):
        return [p for p in self.products if p.get("owner_id") == owner_id]


class FakeLLM:
    """Returns a canned JSON answer shaped like the one each prompt asks for."""

    def __init__(self, reply: str | None = None):
        self.reply = reply
        self.calls = []

    def generate(self, parts):
        self.calls.append(parts)
        if self.reply is not None:
            return self.reply
        text = " ".join(parts)
        if "transcription" in text:
            return json.dumps({"transcription": "(fake transcript)", "summary": "A fake pitch summary.",
                               "pitch_title": "Fake pitch", "pitch_story": "Generated by the fake LLM.",
                               "key_points": ["fake"]})
        if "Marketplace coaching" in text:
            return json.dumps({k: [f"(fake {k} advice)"] for k in (
                "pricing", "bundles", "seo", "photos", "seasonality", "inventory", "promotions", "discounts",
                "new_product_ideas")})
        return json.dumps({"title": "Fake listing title", "short_description": "Fake short description.",
                           "long_description": "Fake long description.", "bullet_points": ["fake"],
                           "seo_tags": ["fake"], "alt_text": "fake"})


class FakeTranscriber:
    def __init__(self, transcript="I make hand-painted Madhubani sarees in my village."):
        self.transcript = transcript

    def transcribe(self, audio_bytes, language_code="en-IN"):
        return self.transcript


class FakeImageEditor:
    def __init__(self):
        self.prompts = []

    def edit(self, image_bytes, prompt, guidance_scale=18):
        self.prompts.append(prompt)
        return TINY_PNG


class FakeCloud:
    def __init__(self):
        self.storage = FakeStorage()
        self.store = FakeStore()
        self.llm = FakeLLM()
        self.transcriber = FakeTranscriber()
        self.image_editor = FakeImageEditor()


_shared = None


def shared() -> FakeCloud:
    global _shared
    if _shared is None:
        _shared = FakeCloud()
    return _shared
